template: Hello, %s!
defaultName: ${DW_DEFAULT_NAME:-Stranger}
logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
  loggers:
    io.whiskyhuntr: DEBUG
swagger:
  resourcePackage: io.whiskyhuntr.core.resources